name: Metrics
on:
  # Trigger every hour
  schedule: [{cron: "0 * * * *"}]
  # Trigger on push to main
  push: {branches: ["main"]}
  # Allow manual triggers from the GitHub UI
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Print GITHUB_WORKSPACE
        run: |
          echo $GITHUB_WORKSPACE, ${{ env.GITHUB_WORKSPACE }}
      # - name: base-activity
      #   uses: zachstence/metrics@master
      #   with:
      #     token: ${{ secrets.METRICS_PAT }}
      #     config_presets: "${{ env.GITHUB_WORKSPACE }}/src/metrics/preset.yml"
      #     filename: assets/metrics/base-activity.svg

      #     base: activity

      # - name: base-metadata
      #   uses: zachstence/metrics@master
      #   with:
      #     token: ${{ secrets.METRICS_PAT }}
      #     config_presets: "${{ env.GITHUB_WORKSPACE }}/src/metrics/preset.yml"
      #     filename: assets/metrics/base-metadata.svg

      #     base: metadata

      # - name: activity
      #   uses: zachstence/metrics@master
      #   with:
      #     token: ${{ secrets.METRICS_PAT }}
      #     config_presets: "${{ env.GITHUB_WORKSPACE }}/src/metrics/preset.yml"
      #     filename: assets/metrics/activity.svg
          
      #     base: ""
      #     plugin_activity: yes
      #     plugin_activity_visibility: public

      # - name: habits-charts
      #   uses: zachstence/metrics@master
      #   with:
      #     token: ${{ secrets.METRICS_PAT }}
      #     config_presets: "${{ env.GITHUB_WORKSPACE }}/src/metrics/preset.yml"
      #     filename: assets/metrics/habits-charts.svg

      #     base: ""
      #     plugin_habits: yes
      #     plugin_habits_from: 1000
      #     plugin_habits_facts: no
      #     plugin_habits_charts: yes
      #     plugin_habits_charts_type: chartist

      # - name: habits-facts
      #   uses: zachstence/metrics@master
      #   with:
      #     token: ${{ secrets.METRICS_PAT }}
      #     config_presets: "${{ env.GITHUB_WORKSPACE }}/src/metrics/preset.yml"
      #     filename: assets/metrics/habits-facts.svg

      #     base: ""
      #     plugin_habits: yes
      #     plugin_habits_from: 1000
      #     plugin_habits_facts: yes
      #     plugin_habits_charts: no

      # - name: isocalendar
      #   uses: zachstence/metrics@master
      #   with:
      #     token: ${{ secrets.METRICS_PAT }}
      #     config_presets: "${{ env.GITHUB_WORKSPACE }}/src/metrics/preset.yml"
      #     filename: assets/metrics/isocalendar.svg

      #     base: ""
      #     plugin_isocalendar: yes
