name: Metrics
on:
  # Trigger every hour
  schedule: [{cron: "0 * * * *"}]
  # Trigger on push to main
  push: {branches: ["main"]}
  # Allow manual triggers from the GitHub UI
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: base-activity
        uses: zachstence/metrics@master
        with:
          filename: assets/metrics/base-activity.svg
          token: ${{ secrets.METRICS_PAT }}
          base: activity

      - name: base-metadata
        uses: zachstence/metrics@master
        with:
          filename: assets/metrics/base-metadata.svg
          token: ${{ secrets.METRICS_PAT }}
          base: metadata
      

# Options
# user: zachstence
# template: classic
# base: activity, metadata
# config_timezone: America/Chicago
# plugin_activity: yes
# plugin_activity_days: 14
# plugin_activity_filter: all
# plugin_activity_limit: 5
# plugin_activity_load: 300
# plugin_activity_visibility: all
# plugin_habits: yes
# plugin_habits_charts: yes
# plugin_habits_charts_type: classic
# plugin_habits_days: 14
# plugin_habits_facts: yes
# plugin_habits_from: 200
# plugin_introduction: yes
# plugin_introduction_title: yes
# plugin_isocalendar: yes
# plugin_isocalendar_duration: half-year
# plugin_languages: yes
# plugin_languages_analysis_timeout: 15
# plugin_languages_categories: markup, programming
# plugin_languages_colors: github
# plugin_languages_limit: 8
# plugin_languages_recent_categories: markup, programming
# plugin_languages_recent_days: 14
# plugin_languages_recent_load: 300
# plugin_languages_sections: most-used
# plugin_languages_threshold: 0%
# plugin_wakatime: yes
# plugin_wakatime_days: 7
# plugin_wakatime_limit: 5
# plugin_wakatime_repositories_visibility: all
# plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
# plugin_wakatime_url: https://wakatime.com
# plugin_wakatime_user: current