# Disabling this job because it is failing. Awaiting a resolution from the maintainers
# https://github.com/vnphanquang/monkeytype-readme/issues/1


# name: Monkeytype Readme

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * 0'

# jobs:
#   update-readme:
#     name: Update this repo's README
#     runs-on: ubuntu-latest
#     steps:
#       - uses: vnphanquang/monkeytype-readme@main
#         with:
#           monkeytype_api_key: ${{ secrets.MONKEYTYPE_API_KEY }}
#           mode: 'words'
#           mode2: '50'
#           style: 'for-the-badge'
#           logoVariant: 'one'
#           label: 'monkeytype'
